[package]
name = "private-voting-client"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "1.1.0", features = ["full"] }
structopt = "0.3.26"
tokio = { version = "1.48.0", features = ["full"] }
